<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/28 05:07:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mvg',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
