<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/28 23:05:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mvg',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
