Jugador:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    user_id:   { type: string(255), notnull: true, unique: true }
    nombre:   { type: string(255), notnull: false }    
    eliminado: { type: boolean, default: 0 }
 
Video:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    url:   { type: string(255), notnull: true }
    nombre:   { type: string(255), notnull: false }
    categoria:   { type: string(255), notnull: false }
    eliminado: { type: boolean, default: 0 }

Intervalo:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    video_id:   { type: integer(4) }
    inicio: { type: time }
    fin: { type: time }
    eliminado: { type: boolean, default: 0 }
  relations:
    Video: { local: video_id, foreign: id, foreignAlias: IntervaloVideo }

Etiqueta:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    texto:   { type: string(255) }
    ponderacion: { type: integer(4) }

Mesa:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    jugador1_id:   { type: integer(4) }
    jugador2_id:   { type: integer(4) }
    tiempo_emparejar: { type:  integer(4) }
    estado:   { type: integer(1) } 
    eliminado: { type: boolean, default: 0 }
  relations:
    Jugador1: { local: jugador1_id, foreign: id, foreignAlias: JugadorMesa1 }
    Jugador2: { local: jugador2_id, foreign: id, foreignAlias: JugadorMesa2 }

RelacionMesaVideo:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    mesa_id:   { type: integer(4) }    
    jugador_id:   { type: integer(4) }
    num_round:   { type: integer(4) }
    intervalo_id: { type: integer(4) }
    #respuesta_real: { type: boolean, default: 0 }
    respuesta_real: {type: integer(1), default: -1}
    eliminado: { type: boolean, default: 0 }
  relations:
    Mesa: { local: mesa_id, foreign: id, foreignAlias: MesaMesaVideo }    
    Jugador: { local: jugador_id, foreign: id, foreignAlias: JugadorMesaVideo }
    Intervalo: { local: intervalo_id, foreign: id, foreignAlias: MesaVideoIntervalo }

InstanciaEtiqueta:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    relacionmesavideo_id:   { type: integer(4) }
    texto:   { type: string(255) }
    tiempo: { type: time }
    eliminado: { type: boolean, default: 0 }
  relations:
    RelacionMesaVideo: { local: relacionmesavideo_id, foreign: id, foreignAlias: InstanciaEtiquetaRelacionMesaVideo }    

Decision:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    relacionmesavideo_id:   { type: integer(4) }
    tiempo: { type: time }
    #respuesta: { type: boolean, default: 0 }
    respuesta: { type: integer(1), default: -1 } #tinyint smallint
    eliminado: { type: boolean, default: 0 }
  relations:
    RelacionMesaVideo: { local: relacionmesavideo_id, foreign: id, foreignAlias: InstanciaEtiquetaRelacionMesaVideo }
    
Puntaje:
  actAs:
    Timestampable:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true, notnull:  true, unique: true }
    token:   { type: string(255), notnull: true, unique: false }
    mesa_id:   { type: integer(4) }    
    jugador_id:   { type: integer(4) }
    puntaje:   { type: integer(4), default: 0 }
  relations:
    Mesa: { local: mesa_id, foreign: id, foreignAlias: MesaPuntaje }    
    Jugador: { local: jugador_id, foreign: id, foreignAlias: JugadorPuntaje }