<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $token
 * @property string $url
 * @property string $nombre
 * @property string $categoria
 * @property boolean $eliminado
 * @property Doctrine_Collection $IntervaloVideo
 * @property Doctrine_Collection $itemcoleccionint2
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getToken()             Returns the current record's "token" value
 * @method string              getUrl()               Returns the current record's "url" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method string              getCategoria()         Returns the current record's "categoria" value
 * @method boolean             getEliminado()         Returns the current record's "eliminado" value
 * @method Doctrine_Collection getIntervaloVideo()    Returns the current record's "IntervaloVideo" collection
 * @method Doctrine_Collection getItemcoleccionint2() Returns the current record's "itemcoleccionint2" collection
 * @method Video               setId()                Sets the current record's "id" value
 * @method Video               setToken()             Sets the current record's "token" value
 * @method Video               setUrl()               Sets the current record's "url" value
 * @method Video               setNombre()            Sets the current record's "nombre" value
 * @method Video               setCategoria()         Sets the current record's "categoria" value
 * @method Video               setEliminado()         Sets the current record's "eliminado" value
 * @method Video               setIntervaloVideo()    Sets the current record's "IntervaloVideo" collection
 * @method Video               setItemcoleccionint2() Sets the current record's "itemcoleccionint2" collection
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('categoria', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('eliminado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Intervalo as IntervaloVideo', array(
             'local' => 'id',
             'foreign' => 'video_id'));

        $this->hasMany('ItemColeccion as itemcoleccionint2', array(
             'local' => 'id',
             'foreign' => 'video2'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}