<?php

/**
 * BaseItemColeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $intervalo1
 * @property integer $intervalo2
 * @property boolean $respuesta_real
 * @property integer $coleccion_id
 * @property Coleccion $Coleccion
 * @property Intervalo $Intervalo
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method integer       getIntervalo1()     Returns the current record's "intervalo1" value
 * @method integer       getIntervalo2()     Returns the current record's "intervalo2" value
 * @method boolean       getRespuestaReal()  Returns the current record's "respuesta_real" value
 * @method integer       getColeccionId()    Returns the current record's "coleccion_id" value
 * @method Coleccion     getColeccion()      Returns the current record's "Coleccion" value
 * @method Intervalo     getIntervalo()      Returns the current record's "Intervalo" value
 * @method ItemColeccion setId()             Sets the current record's "id" value
 * @method ItemColeccion setIntervalo1()     Sets the current record's "intervalo1" value
 * @method ItemColeccion setIntervalo2()     Sets the current record's "intervalo2" value
 * @method ItemColeccion setRespuestaReal()  Sets the current record's "respuesta_real" value
 * @method ItemColeccion setColeccionId()    Sets the current record's "coleccion_id" value
 * @method ItemColeccion setColeccion()      Sets the current record's "Coleccion" value
 * @method ItemColeccion setIntervalo()      Sets the current record's "Intervalo" value
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemColeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_coleccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('intervalo1', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('intervalo2', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('respuesta_real', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('coleccion_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Coleccion', array(
             'local' => 'coleccion_id',
             'foreign' => 'id'));

        $this->hasOne('Intervalo', array(
             'local' => 'intervalo2',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}