<?php

/**
 * BaseItemColeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $video1
 * @property integer $video2
 * @property boolean $respuesta_real
 * @property integer $coleccion_id
 * @property Coleccion $Coleccion
 * @property Video $Video
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method integer       getVideo1()         Returns the current record's "video1" value
 * @method integer       getVideo2()         Returns the current record's "video2" value
 * @method boolean       getRespuestaReal()  Returns the current record's "respuesta_real" value
 * @method integer       getColeccionId()    Returns the current record's "coleccion_id" value
 * @method Coleccion     getColeccion()      Returns the current record's "Coleccion" value
 * @method Video         getVideo()          Returns the current record's "Video" value
 * @method ItemColeccion setId()             Sets the current record's "id" value
 * @method ItemColeccion setVideo1()         Sets the current record's "video1" value
 * @method ItemColeccion setVideo2()         Sets the current record's "video2" value
 * @method ItemColeccion setRespuestaReal()  Sets the current record's "respuesta_real" value
 * @method ItemColeccion setColeccionId()    Sets the current record's "coleccion_id" value
 * @method ItemColeccion setColeccion()      Sets the current record's "Coleccion" value
 * @method ItemColeccion setVideo()          Sets the current record's "Video" value
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemColeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_coleccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('video1', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('video2', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('respuesta_real', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('coleccion_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Coleccion', array(
             'local' => 'coleccion_id',
             'foreign' => 'id'));

        $this->hasOne('Video', array(
             'local' => 'video2',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}