<?php

/**
 * BaseColeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $itemcoleccion
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method Doctrine_Collection getItemcoleccion() Returns the current record's "itemcoleccion" collection
 * @method Coleccion           setId()            Sets the current record's "id" value
 * @method Coleccion           setItemcoleccion() Sets the current record's "itemcoleccion" collection
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coleccion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ItemColeccion as itemcoleccion', array(
             'local' => 'id',
             'foreign' => 'coleccion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}