<?php

/**
 * BaseIntervalo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $token
 * @property integer $video_id
 * @property time $inicio
 * @property time $fin
 * @property integer $total_tags
 * @property boolean $eliminado
 * @property Video $Video
 * @property Doctrine_Collection $MesaVideoIntervalo
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getToken()              Returns the current record's "token" value
 * @method integer             getVideoId()            Returns the current record's "video_id" value
 * @method time                getInicio()             Returns the current record's "inicio" value
 * @method time                getFin()                Returns the current record's "fin" value
 * @method integer             getTotalTags()          Returns the current record's "total_tags" value
 * @method boolean             getEliminado()          Returns the current record's "eliminado" value
 * @method Video               getVideo()              Returns the current record's "Video" value
 * @method Doctrine_Collection getMesaVideoIntervalo() Returns the current record's "MesaVideoIntervalo" collection
 * @method Intervalo           setId()                 Sets the current record's "id" value
 * @method Intervalo           setToken()              Sets the current record's "token" value
 * @method Intervalo           setVideoId()            Sets the current record's "video_id" value
 * @method Intervalo           setInicio()             Sets the current record's "inicio" value
 * @method Intervalo           setFin()                Sets the current record's "fin" value
 * @method Intervalo           setTotalTags()          Sets the current record's "total_tags" value
 * @method Intervalo           setEliminado()          Sets the current record's "eliminado" value
 * @method Intervalo           setVideo()              Sets the current record's "Video" value
 * @method Intervalo           setMesaVideoIntervalo() Sets the current record's "MesaVideoIntervalo" collection
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntervalo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('intervalo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('video_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('inicio', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('fin', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('total_tags', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('eliminado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id'));

        $this->hasMany('RelacionMesaVideo as MesaVideoIntervalo', array(
             'local' => 'id',
             'foreign' => 'intervalo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}