<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/21 20:36:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mvg',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
