<?php

/**
 * BonificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BonificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bonificacion');
    }
}