<?php

/**
 * ColeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coleccion');
    }
}