<?php

/**
 * Coleccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Coleccion extends BaseColeccion
{
    public static function getCountColecciones(){
        $cantidad=Doctrine_Core::getTable('Coleccion')->count();
        return $cantidad;
    }
    public static function obtenerColeccionAleatoria(){
         //Total de colecciones
         $totalColecciones=self::getCountColecciones();
         //Obtener aleatorio colección
         $coleccion_id=mt_rand(1,$totalColecciones);         
         return $coleccion_id;
     }
}