<?php

/**
 * Decision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Decision extends BaseDecision
{
    public static function getDecision($relacionmesavideo_id){                
        $decision=Doctrine_Core::getTable('Decision')
                    ->createQuery('d')                                      
                    ->where('d.relacionmesavideo_id = ?',$relacionmesavideo_id)                    
                    ->fetchOne();        
        return $decision;         
    }
    public static function getResultado($relacionmesavideo_id,$respuesta_real){        
        $resultado="";
        $decision=self::getDecision($relacionmesavideo_id);
        
        if($decision!=NULL){
            $resp=$decision->getRespuesta();
            if($resp!=-1){
                if($resp==$respuesta_real)
                    $resultado="CORRECTO";
                else
                    $resultado="INCORRECTO";
            }else{
                $resultado="NO_CONTESTO";
            }                
        }
        return $resultado;         
    }    
}