<?php

/**
 * DecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Decision');
    }
}