<?php

/**
 * InstanciaEtiqueta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InstanciaEtiqueta extends BaseInstanciaEtiqueta
{
    public static function getInstanciaEtiquetas($relacionmesavideo_id){
        $instanciaetiquetas = Doctrine_Core::getTable('InstanciaEtiqueta')
                ->createQuery('inst')                                
                ->where('inst.relacionmesavideo_id = ?',$relacionmesavideo_id)
                ->fetchArray();
        return $instanciaetiquetas;
    }
    
    //sacar solo etiquetas(texto)  etiquetas(texto,tiempo)
    public static function toJsonInstanciaEtiquetas($instancia_etiquetas){
        $tam_instancia_etiquetas=count($instancia_etiquetas);
        $arr_etiquetas=array();
        for($i=0;$i<$tam_instancia_etiquetas;$i++){            
            $arr_etiquetas[$i]=$instancia_etiquetas[$i]->getTexto();
        }
        return $arr_etiquetas;
    }
}