<?php

/**
 * InstanciaEtiquetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstanciaEtiquetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstanciaEtiquetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstanciaEtiqueta');
    }
}