<?php

/**
 * Intervalo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Intervalo extends BaseIntervalo
{  
    public static function obtenerIntervaloAleatorio($array_excluidos){
         //intervalos ORDENADADOS por total tags
         $intervalos_videos=self::getFragmentoVideosOrdenadosXTags($array_excluidos);
         $tam_intervalos_videos = count($intervalos_videos);
         //echo "intervalovideo: ".$tam_intervalos_videos;
         //Obtener aleatorio
         $id_array = mt_rand(0, $tam_intervalos_videos - 1);
         //$intervalo_jug = $intervalos_videos[$id_array]['id'];         
         $intervalo_jug = $intervalos_videos[$id_array]['id']; 
         return $intervalo_jug;
     }
     //los 15 primeros
     public static function getFragmentoVideosOrdenadosXTags($array_excluidos){
        /*$intervalos_videos=Doctrine_Core::getTable('Intervalo')
                            ->createQuery('i')
                            ->whereNotIn('i.id',$array_excluidos)
                            //->orderBy('i.total_tags')                                     
                            ->fetchArray(); */
        $intervalos_videos = Doctrine_Query::create()
                            ->select('i.id, COUNT(e.id) AS conteo')
                            ->from('Intervalo i')
                            ->leftJoin('i.MesaVideoIntervalo r ON i.id=r.intervalo_id')	
                            ->leftJoin('r.InstanciaEtiquetaRelacionMesaVideo e ON e.relacionmesavideo_id=r.id')			
                            ->whereNotIn('i.id',$array_excluidos)
                            ->groupBy('i.id')
                            ->orderBy('conteo')
                            ->limit(15)
                            ->fetchArray();          
        return $intervalos_videos; 
    }    
    public static function getIntervaloXId($id_intervalo){
        $intervalo_video=Doctrine_Core::getTable('Intervalo')
                    ->createQuery('i')                                      
                    ->where('i.id = ?',$id_intervalo)
                    ->fetchOne();
        return $intervalo_video;        
    }
}