<?php

/**
 * Intervalo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Intervalo extends BaseIntervalo
{  
    public static function getFragmentoVideosOrdenadosXTags(){
        $intervalos_videos=Doctrine_Core::getTable('Intervalo')
                            ->createQuery('i')
                            ->orderBy('i.total_tags')         
                            ->limit(5)
                            ->fetchArray();
        //->fetchArray();
        return $intervalos_videos; 
    }
    public static function getFragmentoVideosOrdenadosXTagsExcluyendo($id_intervalo_excluir){
        $intervalos_videos=Doctrine_Core::getTable('Intervalo')
                            ->createQuery('i')
                            ->where('i.id != ?',$id_intervalo_excluir)
                            ->orderBy('i.total_tags')         
                            ->limit(5)
                            ->fetchArray();
        //->fetchArray();
        return $intervalos_videos; 
    }
}