<?php

/**
 * IntervaloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntervaloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntervaloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Intervalo');
    }
}