<?php

/**
 * ItemColeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ItemColeccion extends BaseItemColeccion
{
     
     public static function getItemsColeccion($coleccion_id){         
        $items_coleccion=Doctrine_Core::getTable('ItemColeccion')
                            ->createQuery('item')
                            ->where('item.coleccion_id=?',$coleccion_id)                            
                            ->fetchArray();
        return $items_coleccion;                 
     }
}