<?php

/**
 * ItemColeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemColeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemColeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemColeccion');
    }
}