<?php

/**
 * Jugador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Jugador extends BaseJugador
{
     public static function getJugadorById($id_jugador){
        $jugador=Doctrine_Core::getTable('Jugador')
                            ->createQuery('j')
                            ->where('j.id= ?',$id_jugador)
                            ->fetchOne();
        return $jugador;
    }
    
    public static function getJugadorByUserId($user_id_facebook){
        $jugador=Doctrine_Core::getTable('Jugador')
                            ->createQuery('j')
                            ->where('j.user_id = ?',$user_id_facebook)
                            ->fetchOne();                
        return $jugador;
    }
    
    public static function getJugadoresDisponibles($id_jugador_no_incluido){
        //antes estado 1 ahora 0 disponible no ocupado
        $jugadores = Doctrine_Core::getTable('Jugador')
                ->createQuery('j')                                
                ->where('j.estado=0 and j.id != ?',$id_jugador_no_incluido)
                ->fetchArray();
        return $jugadores;
    }
}