<?php

/**
 * JugadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JugadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JugadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jugador');
    }
}