<?php

/**
 * Mesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mesa extends BaseMesa
{
     public static function getMesaIncompleta(){
         //'m.id,m.jugador1_id'
        $mesa_incompleta=Doctrine_Core::getTable('Mesa')
                            ->createQuery('m')
                            ->where('m.estado=0')
                            ->limit(1)
                            ->fetchOne();
        return $mesa_incompleta;                 
     }
}