<?php

/**
 * Mesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mesa extends BaseMesa
{
     public static function getMesaIncompleta(){
         //'m.id,m.jugador1_id'
        $mesa_incompleta=Doctrine_Core::getTable('Mesa')
                            ->createQuery('m')
                            ->where('m.estado=0')
                            ->limit(1)
                            ->fetchOne();
        return $mesa_incompleta;                 
     }
     public static function getMesaxId($mesa_id){         
        $mesa=Doctrine_Core::getTable('Mesa')
                            ->createQuery('m')
                            ->where('m.id=?',$mesa_id)                            
                            ->fetchOne();
        return $mesa;                 
     }
     public static function obtenerParejaJuego($user_actual,$mesa_id_jugador1){
            $jugador_pareja_id = 0;
            $jugador_actual = Jugador::getJugadorByUserId($user_actual);

            //SI JUGADOR NUNCA REGISTRADO, AGREGARLO, SINO TOMAR SU ID
            $id_jugador = 0;
            if (!empty($jugador_actual)) {
                $id_jugador = $jugador_actual->getId();
            } else {                
                $jugador_actual = new Jugador();
                $jugador_actual->setUserId($user_actual);
                $jugador_actual->save();
                $id_jugador = $jugador_actual->getId();
            }

            $id_mesa = $mesa_id_jugador1;
            //Buscar una mesa incompleta CON UN SOLO JUGADOR
            $mesa_inc = self::getMesaIncompleta();
            if (!empty($mesa_inc)) { // Si hay MESA INCOMPLETA                
                $jug_partner_id = $mesa_inc->getJugador1Id(); //OBTNER EL JUG QUE ESTA ALLI
                //SI NO ES EL MISMO JUG
                if ($jug_partner_id != $id_jugador) {                    
                    $id_mesa = $mesa_inc->getId();
                    //ACTUALIZAR AL JUGADOR2 QUE ES EL ACTUAL Y COMPLETAR LA MESA

                    $mesa_inc->setJugador2Id($id_jugador);
                    $mesa_inc->setEstado(1);
                    $mesa_inc->save();
               
                    //JUGADOR PARTNER 
                    $jug_partner = Jugador::getJugadorById($jug_partner_id);
                   
                    //JUGADOR ENCONTRADO
                    $jugador_pareja_id = $jug_partner->getId();
                    //echo "mesaa_incompleta ".$id_mesa; die();
                }else{
                    if($id_mesa==0){
                           $mesa = new Mesa(); //NUEVA MESA
                           $mesa->setJugador1Id($id_jugador);
                            $mesa->setEstado(0); //Incompleta
                            $mesa->setTiempoEmparejar(time());
                            $mesa->save();
                            $id_mesa = $mesa->getId();
                            $jugador_pareja_id = 0;
                    }
                }

            } else { // Se quedo la mesa conmigo y estado incompleto  // Crearme una mesa y buscarme quien sera mi competidor---Crear Mesa para ambos
                    if($mesa_id_jugador1==0){
                        $mesa = new Mesa(); //NUEVA MESA
                        $mesa->setJugador1Id($id_jugador);
                        $mesa->setEstado(0); //Incompleta
                        $mesa->setTiempoEmparejar(time());
                        $mesa->save();
                        $id_mesa = $mesa->getId();

                        //JUGADOR ENCONTRADO
                        $jugador_pareja_id = 0;
                        //echo "nueva_mesa ".$id_mesa; die();  
                    }else{
                        //sólo indicar cual es el compañero de esa mesa
                        $mesa=Mesa::getMesaxId($mesa_id_jugador1);
                        //JUGADOR ENCONTRADO
                        if($mesa->getEstado()==1){                       
                            $jugador_pareja_id=$mesa->getJugador2Id();
                            $id_mesa=$mesa_id_jugador1;
                        }
                        //echo "mesa ya esta lista ".$id_mesa; die();  
                    }                                                          
            }           
            //-----------------------------------------------------------------------------------------
            $mesa_jugador=array();
            $mesa_jugador[0]=$jugador_pareja_id;
            $mesa_jugador[1]=$id_mesa;
            return $mesa_jugador;
     }
}