<?php

/**
 * Puntaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Puntaje extends BasePuntaje
{
    /*Puntaje obtenido en una mesa específica del Jugador*/
    public static function getPuntajeXMesaJugId($id_mesa, $id_jug){        
        $puntaje=Doctrine_Core::getTable('Puntaje')
                    ->createQuery('p')                                      
                    ->where('p.mesa_id = ?',$id_mesa)
                    ->andWhere('p.jugador_id = ?',$id_jug)
                    ->fetchOne();
        return $puntaje;        
    }
    /*Puntaje obtenido durantes varias partidas por el Jugador*/
    public static function getPuntajeXJugId($id_jug){        
        $puntaje=Doctrine_Query::create()
                    ->select('SUM(p.puntaje) AS puntos')
                    ->from('Puntaje p')                                    
                    ->where('p.jugador_id = ?',$id_jug)
                    ->fetchOne();        
        return $puntaje;        
    }   
    /*Puntaje más alto obtenido de entre todos los jugadores*/
    public static function getPuntajeMaximo(){
        $puntaje=0;
        $puntajes=Doctrine_Query::create()
                    ->select('SUM(p.puntaje) AS puntos')
                    ->from('Puntaje p')
                    ->groupBy('p.jugador_id')
                    ->orderBy('p.puntaje DESC')
                    ->fetchArray();
        if($puntajes!=NULL)
            $puntaje=$puntajes[0]['puntos'];
        return $puntaje;        
    } 
}