<?php

/**
 * Puntaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Puntaje extends BasePuntaje
{
    /*Puntaje obtenido en una mesa específica del Jugador*/
    public static function getPuntajeXMesaJugId($id_mesa, $id_jug){        
        $puntaje=Doctrine_Core::getTable('Puntaje')
                    ->createQuery('p')                                      
                    ->where('p.mesa_id = ?',$id_mesa)
                    ->andWhere('p.jugador_id = ?',$id_jug)
                    ->fetchOne();
        return $puntaje;        
    }
    /*Puntaje obtenido durantes varias partidas por el Jugador*/
    public static function getPuntajeXJugId($id_jug){        
        $puntaje=Doctrine_Query::create()
                    ->select('SUM(p.puntaje) AS puntos')
                    ->from('Puntaje p')                                    
                    ->where('p.jugador_id = ?',$id_jug)
                    ->fetchOne();        
        return $puntaje;        
    }   
    /*Puntaje más alto obtenido de entre todos los jugadores*/
    public static function getPuntajeMaximo(){
        $puntaje=0;
        $puntajes=Doctrine_Query::create()
                    ->select('SUM(p.puntaje) AS puntos')
                    ->from('Puntaje p')
                    ->groupBy('p.jugador_id')
                    ->orderBy('p.puntaje DESC')
                    ->fetchArray();
        if($puntajes!=NULL)
            $puntaje=$puntajes[0]['puntos'];
        return $puntaje;        
    } 
    /*Puntaje más alto obtenido de entre todos los jugadores*/
    public static function getCategoriaNivel($puntaje){
        $arr_categoria=array();
        if($puntaje>=0 && $puntaje<=300){
            $arr_categoria["id_nivel"]=1;
            $arr_categoria["categoria_nivel"]="Novato";
        }
        if($puntaje>300 && $puntaje<=600){
            $arr_categoria["id_nivel"]=2;
            $arr_categoria["categoria_nivel"]="Amateur";
        }
        if($puntaje>600 && $puntaje<=900){
            $arr_categoria["id_nivel"]=3;
            $arr_categoria["categoria_nivel"]="Intermedio";
        }
        if($puntaje>900 && $puntaje<=1200){
            $arr_categoria["id_nivel"]=4;
            $arr_categoria["categoria_nivel"]="Profesional";
        }
        if($puntaje>1200 && $puntaje<=1500){
            $arr_categoria["id_nivel"]=5;
            $arr_categoria["categoria_nivel"]="Avanzado";
        }
        if($puntaje>1500 && $puntaje<=1800){
            $arr_categoria["id_nivel"]=6;
            $arr_categoria["categoria_nivel"]="Experto";
        }
        if($puntaje>1800){
            $arr_categoria["id_nivel"]=7;
            $arr_categoria["categoria_nivel"]="Cazador de Videos";
        }
        return $arr_categoria;        
    }
}