<?php

/**
 * Puntaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Puntaje extends BasePuntaje
{
    public static function getPuntajeXMesaJugId($id_mesa, $id_jug){
        $puntaje=Doctrine_Core::getTable('Puntaje')
                    ->createQuery('p')                                      
                    ->where('p.mesa_id = ?',$id_mesa)
                    ->andWhere('p.jugador_id = ?',$id_jug)
                    ->fetchOne();
        return $puntaje;        
    }
}