<?php

/**
 * RelacionMesaVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelacionMesaVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelacionMesaVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelacionMesaVideo');
    }
}