<?php

/**
 * RelacionMesaVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RelacionMesaVideo extends BaseRelacionMesaVideo
{
    //'r.id, r.respuesta_real, r.intervalo_id'
    public static function getRelacionMesaVideo($id_mesa, $jugador_duenio, $round_num){
        $relacion_mesa_vid=Doctrine_Core::getTable('RelacionMesaVideo')
                    ->createQuery('r')                                      
                    ->where('r.mesa_id = ?',$id_mesa)
                    ->andWhere('r.jugador_id = ?',$jugador_duenio)
                    ->andWhere('r.num_round = ?',$round_num)
                    ->fetchOne();
        return $relacion_mesa_vid;        
    }
}