<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MusicVideoGame
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
    public static function getVideoxId($id_video){
        $video=Doctrine_Core::getTable('Video')
                            ->createQuery('v')
                            ->where('v.id=?',$id_video)                            
                            ->fetchOne();
        return $video;                 
     }
}